---

- name: Ubuntu Development Playbook
  hosts: localhost
  roles:
    - role: 'aws/cli'
      tags:
        - aws
        - aws:cli
        - development:cli
      when: aws_enabled or awscli_enabled | bool
    - role: 'aws/ebcli'
      tags:
        - aws
        - aws:ebcli
        - development:cli
      when: aws_enabled or awsebcli_enabled | bool
    - role: 'aws/ecscli'
      become: true
      tags:
        - aws
        - aws:ecscli
        - development:cli
      when: aws_enabled or awsecscli_enabled | bool
    - role: dbeaver
      become: true
      tags:
        - dbeaver
        - development:database
      when: dbeaver_enabled | bool
    - role: docker
      become: true
      tags:
        - docker
        - development:infrastructure
      when: docker_enabled | bool
    - role: docker-compose
      become: true
      tags:
        - docker-compose
        - development:infrastructure
      when: docker_compose_enabled | bool
    - role: development/doctl
      tags:
        - doctl
        - development:infrastructure
      when: doctl_enabled | bool
    - role: dots
      tags:
        - dots
      when: dots_enabled | bool
    - role: envchain
      tags:
        - envchain
      when: envchain_enabled | bool
    - role: git
      become: true
      tags:
        - git
      when: git_enabled | bool
    - role: git-flow
      become: true
      tags:
        - git-flow
      when: git_flow_enabled | bool
    - role: goaccess
      tags:
        - goaccess
        - development:infrastructure
      when: goaccess_enabled | bool
    - role: golang/language
      tags:
        - go
        - development:programing
      when: golang_enabled | bool
    - role: golang/assh
      tags:
        - go
        - go:assh
        - development:programing
      when: go_assh_enabled | bool
    - role: htop
      tags:
        - htop
        - development:infrastructure
      when: htop_enabled | bool
    - role: java/openjdk
      tags:
        - java
        - java:openjdk
        - development:programing
      when: java_openjdk_enabled | bool
    - role: java/zulu
      tags:
        - java
        - java:zulu
        - development:programing
      when: java_zulu_enabled | bool
    - role: java/openjre
      tags:
        - java
        - java:openjre
        - development:programing
      when: java_openjre_enabled | bool
    - role: keychain
      tags:
        - keychain
        - development:infrastructure
      when: keychain_enabled | bool
    - role: lens
      become: true
      tags:
        - lens
        - development:editor
      when: lens_enabled | bool
    - role: obsidian
      tags:
        - obsidian
        - development:programing
      when: obsidian_enabled | bool
    - role: python
      tags:
        - python
        - development:programing
      when: python_enabled | bool
    - role: postman
      tags:
        - postman
        - development:programing
      when: postman_enabled | bool
    - role: meld
      become: true
      tags:
        - meld
        - development:programing
      when: meld_enabled | bool
    - role: mysql-client
      become: true
      tags:
        - mysql-client
        - development:database
      when: mysql_client_enabled | bool
    - role: mysql-workbench
      become: true
      tags:
        - mysql-workbench
        - development:database
      when: mysql_workbench_enabled | bool
    - role: ruby/rbenv
      tags:
        - ruby
        - ruby:rbenv
        - development:programing
      when: ruby_enabled | bool
    - role: ssh
      become: true
      tags:
        - ssh
      when: ssh_enabled | bool
    - role: ruby/landscape
      tags:
        - ruby
        - ruby:landscape
        - development:programing
      when: ruby_landscape_enabled | bool
    - role: talend
      tags:
        - talend
        - development:infrastructure
      when: talend_enabled | bool
    - role: terminator
      tags:
        - terminator
        - development
      when: terminator_enabled | bool
    - role: terraform/tfenv
      tags:
        - terraform
        - tfenv
        - development:infrastructure
      when: tfenv_enabled | bool
    - role: terraform/tgenv
      tags:
        - terragrunt
        - tgenv
        - development:infrastructure
      when: tgenv_enabled | bool
    - role: tmux
      become: true
      tags:
        - tmux
      when: tmux_enabled | bool
    - role: vagrant
      become: true
      tags:
        - vagrant
        - development:infrastructure
      when: vagrant_enabled | bool
    - role: virtualbox
      become: true
      tags:
        - virtualbox
        - development:infrastructure
      when: virtualbox_enabled | bool
    - role: virtmanager
      become: true
      tags:
        - virtmanager
        - development:infrastructure
      when: virtmanager_enabled | bool
    - role: vscode
      become: true
      tags:
        - vscode
        - development:infrastructure
      when: vscode_enabled | bool
    - role: zsh
      tags:
        - zsh
      when: zsh_enabled | bool
