---

- name: Download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    owner: root
    group: root
    mode: 0755